// ─── PLACEHOLDER — plant_cold.png ────────────────────────────────────────────
// Replace this stub with actual PNG data generated by tools/convert_image.py.
//
// Recommended image spec:
//   Size   : 64 × 64 px  (adjust PLANT_IMG_W / PLANT_IMG_H in config.h)
//   Format : PNG with alpha channel (RGBA)
//   Content: Plant shivering / cold illustration (triggered below PLANT_TEMP_MIN_C)
//
// Generation command:
//   python tools/convert_image.py src/assets/plant_cold.png
// Then copy the resulting array here and update the size comment.

static const uint8_t PROGMEM plant_cold[] = { 0x00 };
