// ─── PLACEHOLDER — plant_thirsty.png ─────────────────────────────────────────
// Replace this stub with actual PNG data generated by tools/convert_image.py.
//
// Recommended image spec:
//   Size   : 64 × 64 px  (adjust PLANT_IMG_W / PLANT_IMG_H in config.h)
//   Format : PNG with alpha channel (RGBA)
//   Content: Drooping / thirsty plant illustration (triggered when soil_pct < soil_threshold)
//
// Generation command:
//   python tools/convert_image.py src/assets/plant_thirsty.png
// Then copy the resulting array here and update the size comment.

static const uint8_t PROGMEM plant_thirsty[] = { 0x00 };
