; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:pico]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200
lib_deps =
	bodmer/TFT_eSPI@^2.5.43
	bitbank2/PNGdec@^1.1.6
	greiman/SdFat@^2.2.3

; --- Configuration TFT_eSPI pour ILI9342 320x240 natif paysage ---
; ILI9342 = variante ILI9341 avec GRAM 320x240 natif landscape
build_flags =
	-D USE_SPI_ARRAY_TRANSFER=1
	-D SPI_DRIVER_SELECT=0
	-D USER_SETUP_LOADED
	-D ST7789_DRIVER
	-D TFT_WIDTH=240
	-D TFT_HEIGHT=320
	-D TFT_MOSI=3
	-D TFT_SCLK=2
	-D TFT_MISO=4
	-D TFT_CS=6
	-D TFT_DC=5
	-D TFT_RST=4
	-D TFT_BL=7
	-D TFT_BACKLIGHT_ON=HIGH
	-D TFT_RGB_ORDER=0
	-D SPI_FREQUENCY=40000000
	-D LOAD_GLCD
